version: '3.9'

services:
  db:
    image: nouchka/sqlite3
    container_name: db
    volumes:
      - ./server/prisma:/data
    ports:
      - "3306:3306"

  server:
    build: ./server
    container_name: server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
    depends_on:
      - db

  client:
    build: ./client
    container_name: client
    ports:
      - "5173:80"
    depends_on:
      - server
